theme: jekyll-theme-minimal
title: Revista Digital del Diplomado en Metodología de la Investigación Científica
description: Aplicado a la Defensa y la Seguridad Nacional. Un proyecto académico coordinado por Johany Acevedo.
