theme: jekyll-theme-minimal
title: Revista del Diplomado de Metodología de la Investigación Científica Aplicada a la Defensa y Seguridad Nacional_UNADE
description: Compendio de artículos científicos del Diplomado en Metodología de la Investigación resultado de la  ---- .


title: Editora Principal 


title: Co-Editor 



title: Caolaboradores 
